name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Clean Install na raiz
        run: mvn clean install

      - name: Maven Test na raiz
        run: mvn test

      - name: Maven Clean Install no main_app
        working-directory: ./main_app
        run: mvn clean install

      - name: Rodar aplicação Spring Boot no main_app
        working-directory: ./main_app
        run: mvn spring-boot:run
