name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Executar análise estática (Checkstyle)
        run: mvn checkstyle:check
        working-directory: ./main_app

      - name: Executar testes unitários
        run: mvn test
        working-directory: ./main_app

      - name: Gerar relatório de cobertura com JaCoCo
        run: mvn jacoco:prepare-agent test jacoco:report
        working-directory: ./main_app

      - name: Construir artefato
        run: mvn clean package
        working-directory: ./main_app

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: main_app/target/*.jar
